# Generated by Django 3.0.6 on 2020-05-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount_outstanding',
            field=models.FloatField(default=0.0),
        ),
    ]
