# Generated by Django 3.0.6 on 2020-05-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('menu_cat', models.CharField(choices=[('main', 'Main'), ('side', 'Side')], max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_freq', models.IntegerField(default=1)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor')),
            ],
        ),
    ]
